name: Build and deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: ./frontend
        run: pip install -r requirements.txt

      - name: Install Neovim
        run: |
          wget https://github.com/neovim/neovim/releases/download/v0.11.5/nvim-linux-x86_64.tar.gz
          tar -xzf nvim-linux-x86_64.tar.gz
          echo "$PWD/nvim-linux-x86_64/bin" >> $GITHUB_PATH

      - name: Install cent.vim
        run: |
          git clone https://github.com/centlang/cent.vim \
            ~/.config/nvim/pack/vendor/start/cent.vim

      - name: Build
        working-directory: ./frontend
        run: python build.py

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
